name: Jest Tests

on: [push]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node 15
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: install deps
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
